### ISSUE TITLE
Create templates for issues and pull requests

### ISSUE THREAD

**Issue by hoegertn** [open-constructs/aws-cdk-library#29]
It would be great to have templates for issues and pull requests.
Ideas can be borrowed from the CDK project.

Issues:
* several types for bugs, features, chores
* Call to action for community to take issues

PRs:
* checklist for contributors
* checklist for reviewers and maintainers
* information for correct PR titles

**Comment by dbartholomae** [comment]
I've researched a bit around this when setting up https://github.com/dbartholomae/lambda-middleware and preparing for Hacktoberfest a few years ago. Here's the Issue templates I ended up with:
https://github.com/dbartholomae/lambda-middleware/tree/main/.github/ISSUE_TEMPLATE

I'll open a PR shortly to add them here so we can discuss in the PR whether they work, as well as any changes needed.
