### ISSUE TITLE
Package Manager Decision: Yarn vs NPM vs PNPM

### ISSUE THREAD

**Issue by mrgrain** [open-constructs/aws-cdk-library#9]
The default in projen is currently Yarn Classic, but that doesn't mean we can't choose anything else.
The options are:

- Yarn Classic
- Yarn Berry
- NPM
- PNPM

I believe Yarn Classic is out of date and does not provide any benefits over other package managers (especially NPM) anymore. To the contrary, it has some annoying differences that won't ever get fixed. (Examples: Can't use local files with an `@` in the file name. Different peer dep behavior)

(Modern) Yarn Berry support is unfortunately still patchy in projen.

I love PNPM, but believe it is too obscure and simply not needed for most projects.

**I therefor propose we switch to NPM.**
NPM is the default for most users and is speed-wise probably on par with yarn classic. It also supports basic workspaces if we ever want that. And while NPM might not be at the forefront of new features, they are definitely catching up.

Happy to create the PR and ADR if maintainers agree.

**Comment by hoegertn** [comment]
I am fine with this. Benefit is that NPM is available without installing stuff or using custom build images

**Comment by mbonig** [comment]
Agreed, I'm fine with NPM. I've seen a few problems with various versioning with NPM but if that comes up, let's solve them (instead of my lazy 'I'll just use yarn instead' approach)

**Comment by go-to-k** [comment]
I like pnpm, but I agree with you. I think npm is good in this library for now.

**Comment by hoegertn** [comment]
@mrgrain is the PR what you envisioned?

**Comment by mrgrain** [comment]
Yes absolutely

**Comment by dbartholomae** [comment]
Nice work! :)
